In [1]:
import numpy
import math
import cv2
from PIL import Image
from numpy import mean
from numpy import cov
from numpy.linalg import eig
from numpy.linalg import inv 

In [2]:
def load_mnist(path, kind='train'):
    import os
    import gzip
    import numpy as np

    """Load MNIST data from `path`"""
    labels_path = os.path.join(path,
                               '%s-labels-idx1-ubyte.gz'
                               % kind)
    images_path = os.path.join(path,
                               '%s-images-idx3-ubyte.gz'
                               % kind)

    with gzip.open(labels_path, 'rb') as lbpath:
        labels = np.frombuffer(lbpath.read(), dtype=np.uint8,
                               offset=8)

    with gzip.open(images_path, 'rb') as imgpath:
        images = np.frombuffer(imgpath.read(), dtype=np.uint8,
                               offset=16).reshape(len(labels), 784)

    return images, labels

In [6]:
images, Y = load_mnist('../fMNIST', kind='train')
images_test, label1 = load_mnist('../fMNIST', kind='t10k') 

In [7]:
def PCA(images,dimensionToProject):
    # calculate the mean of each column
    M = mean(numpy.array(images).T.tolist(), axis=1)
    # center columns by subtracting column means

    C = images - M
    # calculate covariance matrix of centered matrix
    V = cov(C.T)
    # eigendecomposition of covariance matrix
    values, vectors = eig(V)
    vectors = vectors[:numpy.shape(vectors)[0],0:dimensionToProject]
    # project data
    P = (vectors.T.dot(C.T)).T
    
    return (numpy.real(P))

In [37]:
trainX = PCA(images,50)
image1 = PCA(images_test,50)

In [13]:
trainY = numpy.zeros((Y.shape[0],10))
for i in range(len(Y)):
    trainY[i][Y[i]] = 1
print (trainY)
print (Y)

[[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[9 0 0 ... 3 0 5]


In [ ]:
from mnist import MNIST
import numpy as np
import random
mndata = MNIST('Samples')

trainX, trainY= mndata.load_training()

image1, label1 = mndata.load_testing()
import matplotlib.pyplot as plt
plt.plot(trainX[0:100])
#print(np.shape(trainX))
for i in range(0,len(trainX)):
    trainX[i].insert(0,1)
trainX = np.asarray(trainX).T
trainY = np.asarray(trainY).T
#print(np.shape(trainX))
#print(trainX[0])

In [16]:

import numpy as np
W = np.dot(np.dot(np.linalg.inv(np.dot(trainX.T,trainX)),trainX.T),np.asarray(trainY))
#print(np.dot(np.linalg.inv(np.dot(trainX.T,trainX)),np.dot(trainX.T,trainX)))

W = np.reshape(W,(W.shape[0],10))

In [18]:
print(W.shape)

(50, 10)


In [32]:
def accuracy(X,y):
    acc = 0
    for i in range(len(X)):
        p = W.T@X[i]
        if(y[i] == np.where(p == max(p))[0]):
            acc +=1
    return (acc/X.shape[0])

In [33]:
print (trainX.shape)
print (Y.shape)

(60000, 50)
(60000,)


In [34]:
acc= accuracy(trainX,Y)

In [35]:
print (acc)

0.7902666666666667


In [38]:
print (image1.shape)

(10000, 50)


In [39]:
print (label1.shape)

(10000,)
