In [1]:
import csv
import numpy as np
from matplotlib import pyplot as plt
from sklearn.svm import SVC
# reading csv file to extract data into numpy array
with open('Medical_data.csv', 'r') as f:
    medical = list(csv.reader(f, delimiter=','))
    med_data = np.array(medical)

# separating feature and label
X = med_data[1:,1:].astype('float')   # feature matrix
y = med_data[1:,0]  # label of input
print (X)
print (y) 

[[ 1.63151556 -0.26444658  2.53456715]
 [ 0.15395105  1.41953348  1.33312079]
 [ 2.02172912  0.26204638  2.87997174]
 ...
 [ 0.19320188  0.36039894  1.86764457]
 [ 1.68409597 -0.0232182   3.30625768]
 [ 0.9752179   2.30595893  0.22982688]]
['HEALTHY' 'SURGERY' 'HEALTHY' ... 'HEALTHY' 'HEALTHY' 'MEDICATION']


In [2]:
classes = ['HEALTHY','SURGERY','MEDICATION']

In [3]:
def multiclassSVM(X,Y,classes):
    f = X.shape[1]
    n = X.shape[0]
    c = len(classes)
    W = np.zeros((c,f))
    b = np.zeros((c))
    for i in range(c):
        Ty = np.zeros((n))
        for j in range(n):
            if Y[j] == classes[i]:
                Ty[j] = 1
            else:
                Ty[j] = -1
        clf = SVC(C = 10, kernel = 'linear')
        clf.fit(X, Ty.ravel())
        W[i],b[i] = clf.coef_[0],clf.intercept_
    return W,b

In [4]:
W,b = multiclassSVM(X,y,classes)

In [5]:
def accuracy(X,Y,W,b,classes):
    c = len(classes)         #number of classes
    n = X.shape[0]           #number of data samples
    f = W.shape[1]           #input dimension
    acc = 0                  #number of correctly classified inputs
    
    # implementing soft-max to calculate predicted class
    g = np.zeros(c)     # probability for each class
    for i in range(n):
        g = np.exp((W@X[i].reshape(f,1)).reshape(c)+b)
        y_predicted = np.where(g == max(g))
        if (y_predicted[0] == classes.index(Y[i])):
            acc += 1
    
    return acc/X.shape[0]

In [6]:
acc = accuracy(X,y,W,b,classes)
print (acc*100)

81.8


In [7]:
print (W)

[[ 1.14693497 -0.55799118  0.91321611]
 [-1.62521277  0.2824707   0.44772902]
 [ 0.24025416  0.05744672 -1.63714355]]


In [8]:
print (b)

[-3.02171992 -0.15317589  0.5146363 ]
